name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker
        run: docker --version

      - name: Build da imagem
        run: docker build -t landing-page .

  terraform:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform
        working-directory: infra
        run: terraform init

      - name: Validate Terraform
        working-directory: infra
        run: terraform validate
